	.title	TSFPGA	
	.enabl	LC
	
	.asect					; needed for my linker
	.=1000

START:	mtps	#200				; stop interrupts
	mov	#1000, SP

	; run PPU code
	mov	#PPUSTA, R4			; run PPU code
	mov	#PPUEND-PPUSTA/2, R5
	call	PPRUN				; CPU will stop after some..

	; setup CPU vsync
	mov	@#100, -(SP)
	mov	@#102, -(SP)
	mov	#VsyInt, @#100
	mov	#200, @#102

	; wait 'a bit' for PPU
	clr	R0
	sob	R0, .

	; main CPU 'program'
	mtps	#0
10$:	cmp	CNT12, #500.
	blo	10$

	; restore used addrs
	mtps	#200
	mov	(SP)+, @#102
	mov	(SP)+, @#100
	mtps	#0

	; wait for PPU to finish
20$:	tst	PPFIN
	bne	20$
	call	PPREL

	; output results
	mov	#MsgCpu, R0
	call	PriStr
	mov	CNT11, R0
	call	PriDec
	mov	CNT12, R0
	call	PriDec
	mov	#MsgPpu, R0
	call	PriStr
	mov	CNT21, R0
	call	PriDec
	mov	CNT22, R0
	call	PriDec
	
	emt	350


CNT21:	.word	0
CNT22:	.word	0

VSYINT:	inc	(PC)+
CNT11:	.word	0
	inc	(PC)+
CNT12:	.word	0
	rti

; print character with channel 0
PriChr:	tstb	@#177564
	bpl	.-4
	movb	R0, @#177566
	return

; print string with channel 0
PriStr:	; emt	351
	; return
	mov	R1, -(SP)
10$:	movb	(R0)+, R1
	beq	99$
	tstb	@#177564
	bpl	.-4
	movb	R1, @#177566
	br	10$
99$:	mov	(SP)+, R1
	return

; print decimal number
PriDec:	mov	R1, -(SP)
	mov	R2, -(SP)
	mov	R3, -(SP)
	mov	#MsgNum+6, R2
	mov	#5., R3
10$:	mov	R0, R1
	clr	R0
	div	#10., R0			; R0:R1 / 10. -> R0 - quotient, R1 - reminder
	add	#'0, R1
	movb	R1, -(R2)
	sob	R3, 10$
	mov	#MsgNum, R0
	mov	(SP)+, R3
	mov	(SP)+, R2
	mov	(SP)+, R1
	br	PriStr

MsgNum:	.asciz	"000000 "
MsgCpu:	.asciz	"CPU: "
MsgPpu:	.asciz	"PPU: "
	.even

; command to PPU
PPCOMM:	.word	177777

; PPU message
PPMSG:	.word	PPARR				; address of beginning of array
        .word	177777				; end of transmission

; PPU data exchange array
PPARR:	.byte	0				; return value (0 - OK)
PPCMD:	.byte	0				; command
	.word	32				; device type (32 - PPU mem)
PPAPP:	.word	0				; address for PPU
PPACP:	.word	0				; address for CPU
PPLEN:	.word	0				; length in words

; send command to PPU with exch array
PPSEN:	mov	#PPMSG, R0			; array address
	mov	#5, R1				; bytes to send+1 (sending from @#PP_MSG)
	br	1$
2$:	movb	(R0)+, @#176676
1$:	tstb	@#176674			; test if we are ready to send
	bpl	1$				; cycle if >= 0 (not set last bit in byte)
	sob	R1, 2$
	return

; send and start PPU code
; R4 - start addr in CPU
; R5 - length / 2
PPRUN:	movb	#1, PPCMD			; 1 - allocate memory
	mov	R5, PPACP
	call	PPSEN				; (!) warn - no testing for success
	movb	#20, PPCMD			; 20 - write to PPU mem
	mov 	R4, PPACP
	mov	R5, PPLEN
	call	PPSEN
	movb	#30, PPCMD			; 30 - run
	br	PPSEN

; release PPU memory (not needed here)
PPREL:	movb	#2, PPCMD			; 2 - release memory
	br	PPSEN


; //////////////////////////////////////////////////////////////////////////////	
; // PPU code
; //////////////////////////////////////////////////////////////////////////////

PPUSTA:	mtps	#200				; no interrupts

	; backup used addrs
	mov	@#100, -(SP)
	mov	@#102, -(SP)
	mov	@#177054, -(SP)

	bic	#^B0000001000000000, @#177054	; enable vsync in CPU
	bic	#^B0000000100000000, @#177054	; enable vsync in PPU

	; setup PPU vsync
	mov	PC, R0
	add	#PPVSYI-., R0
	mov	R0, @#100
	mov	#200, @#102

	; main PPU 'program'
	mtps	#0
10$:	cmp	PPVS02, #400.
	blo	10$
	mtps	#200

	; write counters
	mov	#CNT21/2, @#177010
	mov	PPVS01, @#177014
	mov	#CNT22/2, @#177010
	mov	PPVS02, @#177014

	; restore used addrs
	mov	(SP)+, @#177054
	mov	(SP)+, @#102
	mov	(SP)+, @#100

	; signal to CPU that we are finished in PPU
	mov	#PPFIN/2, @#177010
	clr	@#177014

	mtps	#0
	return


PPVSYI:	inc	(PC)+
PPVS01:	.word	0
	inc	(PC)+
PPVS02:	.word	0
	rti

PPFIN:	.word	177777

PPUEND:

	.END	START
