	.title	TSTME2
	.enabl	LC
	
	.asect					; needed for my linker
	.=1000

START:	mtps	#200				; stop interrupts
	mov	#1000, SP
	mov	#PPUSTA, R4			; run PPU code
	mov	#PPUEND-PPUSTA/2, R5
	call	PPRUN				; CPU will stop after some..

	mov	#176640, R4
	mov	#176642, R5
	mov	#123456, R0
10$:	mov	#10000, R3
	mov	#100000, (R4)
20$:	xor	R0, (R5)
	inc	(R4)
	sob	R3, 20$
	br	10$

; command to PPU
PPCOMM:	.word	177777

; PPU message
PPMSG:	.word	PPARR				; address of beginning of array
        .word	177777				; end of transmission

; PPU data exchange array
PPARR:	.byte	0				; return value (0 - OK)
PPCMD:	.byte	0				; command
	.word	32				; device type (32 - PPU mem)
PPAPP:	.word	0				; address for PPU
PPACP:	.word	0				; address for CPU
PPLEN:	.word	0				; length in words

; send command to PPU with exch array
PPSEN:	mov	#PPMSG, R0			; array address
	mov	#5, R1				; bytes to send+1 (sending from @#PP_MSG)
	br	1$
2$:	movb	(R0)+, @#176676
1$:	tstb	@#176674			; test if we are ready to send
	bpl	1$				; cycle if >= 0 (not set last bit in byte)
	sob	R1, 2$
	return

; send and start PPU code
; R4 - start addr in CPU
; R5 - length / 2
PPRUN:	movb	#1, PPCMD			; 1 - allocate memory
	mov	R5, PPACP
	call	PPSEN				; (!) warn - no testing for success
	movb	#20, PPCMD			; 20 - write to PPU mem
	mov 	R4, PPACP
	mov	R5, PPLEN
	call	PPSEN
	movb	#30, PPCMD			; 30 - run
	br	PPSEN

; release PPU memory (not needed here)
PPREL:	movb	#2, PPCMD			; 2 - release memory
	br	PPSEN


; //////////////////////////////////////////////////////////////////////////////	
; // PPU code
; //////////////////////////////////////////////////////////////////////////////

PPUSTA:	mtps	#200				; no interrupts

	; stop CPU
	clr	@#177076			; stop channel 0 interrupts
	bis	#20, @#177716
	bis	#40, @#177716			; set ACLO, DCLO (bits: 4-CPU HALT mode, 5-CPU stop)
	; mov	#0, @#177716			; remove DCLO
	; mov	#100000, @#177716		; remove ACLO
	; mov	#1, @#177076			; allow channel 0 interrupts
	br .

PPUEND:

	.END	START
